### ISSUE TITLE
windows下的运行问题

### ISSUE THREAD

**Issue by xingyuezhiji** [Urinx/WeixinBot#103]
在windows上登陆成功之后就没反应了，什么回事呀？
[_] 获取联系人 ... https://wx.qq.com/cgi-bin/mmwebwx-bin
成功
[32m2016-10-14 15:47:35[0m [35mDESKTOP-V5952HU[0m [34mroot[4672][0m [30mDEBUG[0m [32m[_] 获取联系人 ... ... 成功[0m
[_] 应有 389 个联系人，读取到联系人 389 个
[_] 共有 4 个群 | 215 个直接联系人 | 0 个特殊账号 ｜ 170 公众号或服务号
[_] 获取群 ... 成功
[32m2016-10-14 15:47:36[0m [35mDESKTOP-V5952HU[0m [34mroot[4672][0m [30mDEBUG[0m [32m[_] 获取群 ... ... 成功[0m
[32m2016-10-14 15:47:37[0m [35mDESKTOP-V5952HU[0m [34mroot[4672][0m [30mDEBUG[0m [32m[_] 微信网页版 ... 开动[0m
[32m2016-10-14 15:47:37[0m [35mDESKTOP-V5952HU[0m [34mroot[4672][0m [30mDEBUG[0m [32m=========================
[#] Web Weixin
[#] Debug Mode: False
[#] Uuid: gY-J2hD0_w==
[#] Uin: 1782313240
[#] Sid: icifNYbWJZSTdUPK
[#] Skey: @crypt_1129107_35bf0dbcbc5d33cc006958253f60fb25
[#] DeviceId: e270213943211471
[#] PassTicket: R2oQ5Bn6ny0J3L44gEVRq8WJg4ngPzzZwLrxULBwlnEvuVNZWCEUW%2FGbDLeI2CnF
=========================[0m
[_] 自动回复模式 ... 关闭
[32m2016-10-14 15:47:37[0m [35mDESKTOP-V5952HU[0m [34mroot[4672][0m [30mDEBUG[0m [32m[*] 自动回复模式 ... 关闭[0m

Traceback (most recent call last):
  File "C:\Users\zhong\Desktop\python\WeixinBot-master (2)\WeixinBot-master\weixin.py", line 1084, in <module>
    webwx.start()
  File "C:\Users\zhong\Desktop\python\WeixinBot-master (2)\WeixinBot-master\weixin.py", line 30, in wrapper
    return fn(*args)
  File "C:\Users\zhong\Desktop\python\WeixinBot-master (2)\WeixinBot-master\weixin.py", line 920, in start
    listenProcess.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\multiprocessing\forking.py", line 67, in dispatcher
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 731, in save_inst
    save(stuff)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle thread.lock objects

**Comment by fofc12** [comment]
确实存在这样的问题。

**Comment by xingyuezhiji** [comment]
有什么解决方法吗

**Comment by xdx3000** [comment]
先解决编码问题再说吧。试试 string.decode(encoding)
