### ISSUE TITLE
同步线路webpush和webpush2都返回‘1100’

### ISSUE THREAD

**Issue by sharpdeep** [Urinx/WeixinBot#12]
在win下测试出现上面问题，在linux下测试正常

**Comment by yong9900** [comment]
很有可能是编码问题。
我这里用linux， 两个都不过，返回1100. 我再检查一下cookie，再就没招了

**Comment by juehai** [comment]
我在 Mac 和 Linux 下都是不行的。

我对比了一下 Web 端JS 请求的synccheck request，我发现 synckey 比 bot 发出去的要长

Web_synckey:1_xxx|2_xxx|3_xxx|11_xxx|13_xxx|201_xxx|1000_xxx

Bot_synckey:'SyncKey': {'Count': 4, 'List': [{'Key': 1, 'Val':xxx}, {'Key': 2, 'Val': xxx}, {'Key': 3, 'Val': xxx}, {'Key': 1000, 'Val': xxx}]},

Web是 1,2,3,11,13,201,1000
但是Bot只有 1,2,3,1000

**Comment by juehai** [comment]
@yong9900 看起来可能和地域有关。

我在北京的 IDC 里运行这个SyncCheck 是能通过的，但是在其他地方就不行了。

你在哪里？

**Comment by sharpdeep** [comment]
@juehai 我是在广东，但是我在linux下测试是可以，换了win7测试就找不到线路了。
@yong9900 我在[0x5e](https://github.com/0x5e)的[wechat-deleted-friends](https://github.com/0x5e/wechat-deleted-friends)找到了这个：

```
        # push_uri与base_uri对应关系(排名分先后)(就是这么奇葩..)
        services = [
            ('wx2.qq.com', 'webpush2.weixin.qq.com'),
            ('qq.com', 'webpush.weixin.qq.com'),
            ('web1.wechat.com', 'webpush1.wechat.com'),
            ('web2.wechat.com', 'webpush2.wechat.com'),
            ('wechat.com', 'webpush.wechat.com'),
            ('web1.wechatapp.com', 'webpush1.wechatapp.com'),
        ]
```

你可以换其他的同步线路试一下。
在linux下我测试webpush2成功，在win下测试都失败了，最后一个好像不是有效地址。

**Comment by Urinx** [comment]
@sharpdeep 已更新 :smiley:

**Comment by juehai** [comment]
赞！我这里成功了。 最后选了 webpush.weixin.qq.com 貌似一直在变，昨天我试了这个不行，今天可以了。

**Comment by sharpdeep** [comment]
测试了一下，最后能用的synchost有

```
            'webpush.weixin.qq.com',
            'webpush1.weixin.qq.com',
            'webpush2.weixin.qq.com',
            'webpush.wechat.com',
            'webpush1.wechat.com',
            'webpush2.wechat.com',
            'webpush1.wechatapp.com',
```

然而我还是找不到测试成功的,坑人的win

**Comment by 0x5e** [comment]
@sharpdeep 我在微信网页版里找来的。。。不清楚为什么要分这么多地址= =

**Comment by sharpdeep** [comment]
@0x5e 也不清楚选择synchost的策略是什么，好像也不是根据base_uri，我的base_uri是wx2.qq.com的时候都失败了

**Comment by imaqqqq** [comment]
我的一直webpush,webpush1和webpush2都不行

**Comment by stonexer** [comment]
e.indexOf("wx2.qq.com") > -1 ? (t = "weixin.qq.com", o = "file2.wx.qq.com", n = "webpush2.weixin.qq.com") : e.indexOf("qq.com") > -1 ? (t = "weixin.qq.com", o = "file.wx.qq.com", n = "webpush.weixin.qq.com") : e.indexOf("web1.wechat.com") > -1 ? (t = "wechat.com", o = "file1.wechat.com", n = "webpush1.wechat.com") : e.indexOf("web2.wechat.com") > -1 ? (t = "wechat.com", o = "file2.wechat.com", n = "webpush2.wechat.com") : e.indexOf("wechat.com") > -1 ? (t = "wechat.com", o = "file.wechat.com", n = "webpush.wechat.com") : e.indexOf("web1.wechatapp.com") > -1 ? (t = "wechatapp.com", o = "file1.wechatapp.com", n = "webpush1.wechatapp.com") : (t = "wechatapp.com", o = "file.wechatapp.com", n = "webpush.wechatapp.com");

**Comment by yong9900** [comment]
我这里也是webpush 
看stonexer的这段code很明显了

**Comment by nmweizi** [comment]
同样环境，在win10下错误，在同一个物理机中的虚机linux中是成功的。看提示信息，证书CertificateError:错误。难道是win10下pyopenssl和linux下实现的不一样，还是版本不一样。

[_] 进行同步线路测试 ... Process Process-1:
Traceback (most recent call last):
  File "d:\python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "d:\python27\lib\multiprocessing\process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "D:\python\WeixinBot\weixin.py", line 426, in listenMsgMode
    self._run('[_] 杩涜鍚屾绾胯矾娴嬭瘯 ... ', self.testsynccheck)
  File "D:\python\WeixinBot\weixin.py", line 526, in _run
    if func(_args): print '鎴愬姛'
  File "D:\python\WeixinBot\weixin.py", line 240, in testsynccheck
    [retcode, selector] = self.synccheck()
  File "D:\python\WeixinBot\weixin.py", line 255, in synccheck
    data = self._get(url)
  File "D:\python\WeixinBot\weixin.py", line 557, in _get
    response = urllib2.urlopen(request)
  File "d:\python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "d:\python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "d:\python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "d:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "d:\python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "d:\python27\lib\urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "d:\python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "d:\python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "d:\python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "d:\python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "d:\python27\lib\httplib.py", line 859, in send
    self.connect()
  File "d:\python27\lib\httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "d:\python27\lib\ssl.py", line 352, in wrap_socket
    _context=self)
  File "d:\python27\lib\ssl.py", line 579, in __init__
    self.do_handshake()
  File "d:\python27\lib\ssl.py", line 816, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "d:\python27\lib\ssl.py", line 271, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
CertificateError: hostname 'webpush1.wechatapp.com' doesn't match either of 'web
push1.wechat.com', 'webpush.wechat.com', 'login.web.wechat.com', 'webpush.web.we
chat.com', 'webpush2.wechat.com', 'webpush.web2.wechat.com', 'file.web2.wechat.c
om', 'web1.wechat.com', 'file.web.wechat.com', 'loginpoll.wechat.com', 'web2.wec
hat.com', 'login.wechat.com', 'login.web2.wechat.com', 'res.wechat.com', 'web.we
chat.com'

**Comment by reverland** [comment]
@juehai synckey在不断变化的，最开始都很短，后来随着webwxsync不断不知道为啥就变长了

**Comment by sbilly** [comment]
现在这个现象还存在吗？

**Comment by sharpdeep** [comment]
@sbilly 这个问题一直存在，而且只是在win系统上出现，同物理机上的linux测试正常

**Comment by sbilly** [comment]
@sharpdeep 这个和 #1 是不是一个问题？

**Comment by sharpdeep** [comment]
@sbilly 情况是一样的，但是好像并不是由于地域不同分流造成的，因为一直在同一个地方，redirect_uri也是不变的，不同的只是操作系统改变了而已

**Comment by lightcax** [comment]
win 也是同步线路失败

**Comment by xo0** [comment]
[_] 进入消息监听模式 ... 成功
2016-03-25 03:23:25 mot root[4969] DEBUG [_] 进入消息监听模式 ... 成功
[_] 进行同步线路测试 ... 2016-03-25 03:23:31 mot root[4969] DEBUG https://webpush.weixin.qq.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_643415476%7C2_643415813%7C3_643415744%7C1000_1458694020&skey=%40crypt_f3aa6e8d_c2bb8f23fd5dc7a3fdbfc5418aac5fcb&uin=181595356&r=1458847405&deviceid=e507851031798318&sid=ntDd8bHuNgLGvefP&_=1458847405
2016-03-25 03:23:32 mot root[4969] DEBUG https://webpush2.weixin.qq.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_643415476%7C2_643415813%7C3_643415744%7C1000_1458694020&skey=%40crypt_f3aa6e8d_c2bb8f23fd5dc7a3fdbfc5418aac5fcb&uin=181595356&r=1458847411&deviceid=e507851031798318&sid=ntDd8bHuNgLGvefP&_=1458847411
2016-03-25 03:23:33 mot root[4969] DEBUG https://webpush.wechat.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_643415476%7C2_643415813%7C3_643415744%7C1000_1458694020&skey=%40crypt_f3aa6e8d_c2bb8f23fd5dc7a3fdbfc5418aac5fcb&uin=181595356&r=1458847412&deviceid=e507851031798318&sid=ntDd8bHuNgLGvefP&_=1458847412
2016-03-25 03:23:33 mot root[4969] DEBUG https://webpush1.wechat.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_643415476%7C2_643415813%7C3_643415744%7C1000_1458694020&skey=%40crypt_f3aa6e8d_c2bb8f23fd5dc7a3fdbfc5418aac5fcb&uin=181595356&r=1458847413&deviceid=e507851031798318&sid=ntDd8bHuNgLGvefP&_=1458847413
2016-03-25 03:23:35 mot root[4969] DEBUG https://webpush2.wechat.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_643415476%7C2_643415813%7C3_643415744%7C1000_1458694020&skey=%40crypt_f3aa6e8d_c2bb8f23fd5dc7a3fdbfc5418aac5fcb&uin=181595356&r=1458847413&deviceid=e507851031798318&sid=ntDd8bHuNgLGvefP&_=1458847413
2016-03-25 03:23:36 mot root[4969] DEBUG https://webpush1.wechatapp.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_643415476%7C2_643415813%7C3_643415744%7C1000_1458694020&skey=%40crypt_f3aa6e8d_c2bb8f23fd5dc7a3fdbfc5418aac5fcb&uin=181595356&r=1458847415&deviceid=e507851031798318&sid=ntDd8bHuNgLGvefP&_=1458847415
失败
[_] 退出程序
2016-03-25 03:23:36 mot root[4969] DEBUG [_] 进行同步线路
2016-03-25 03:23:36 mot root[4969] DEBUG [_] 退出程序
Nonez

win  inux测试失败

**Comment by JokerQyou** [comment]
Hmm，我不确定遇到的是不是同一个问题，放在服务器上跑，大概一天左右（20小时或者更短）出现连续的 `retcode: 0, selector: 4` 后面没有了网络操作，隔了快 50 分钟左右突然出现 `retcode: 1100, selector: 0` 被登出了。我在手机微信里查看，web 端确实已经不在登陆状态。

**Comment by jwpttcg66** [comment]
mac 下也会出现这个问题，全部测试失败，无法同步消息
