### ISSUE TITLE
启动weixin.py失败

### ISSUE THREAD

**Issue by star7th** [Urinx/WeixinBot#128]
Traceback (most recent call last):
  File "weixin.py", line 1159, in <module>
    webwx.start()
  File "weixin.py", line 32, in wrapper
    return fn(*args)
  File "weixin.py", line 927, in start
    self.genQRCode()
  File "weixin.py", line 161, in genQRCode
    self._str2qr('https://login.weixin.qq.com/l/' + self.uuid)
  File "weixin.py", line 1035, in _str2qr
    qr.print_ascii(invert=True)
  File "/usr/lib/python2.6/site-packages/qrcode/main.py", line 249, in print_ascii
    out.write(codes[pos])
  File "/usr/lib64/python2.6/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2588' in position 0: ordinal not in range(128)

**Comment by star7th** [comment]
我尝试绕过生产二维码这一步。直接将url复制到浏览器打开。扫描二维码，命令行提示登录成功，成功获取到了联系人数目，最后在这里出错了：
[*] 自动回复模式 ... 关闭
2016-11-22 15:39:49 localhost.localdomain root[1564] DEBUG [*] 自动回复模式 ... 关闭
[*] 进入消息监听模式 ... 成功
2016-11-22 15:39:49 localhost.localdomain root[1569] DEBUG [*] 进入消息监听模式 ... 成功
[*] 进行同步线路测试 ... 2016-11-22 15:39:49 localhost.localdomain root[1569] DEBUG https://webpush.weixin.qq.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_645442450%7C2645443071%7C3_645442900%7C1000_1479774601&skey=%40crypt_f2a9b885_c3b306210f4481ac9f75f31772c5947&uin=2084815720&r=1479800389&deviceid=e074646143941630&sid=eGeTg%2BpC9x2Y8rO&_=1479800389
2016-11-22 15:39:49 localhost.localdomain root[1569] DEBUG https://webpush.wechat.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_645442450%C2_645443071%7C3_645442900%7C1000_1479774601&skey=%40crypt_f2a9b885_c3b306210f4481ac9f7f3177c2c5947&uin=2084815720&r=1479800389&deviceid=e074646143941630&sid=eGeTg%2BpC9x2Y8rO&_=1479800389
2016-11-22 15:39:50 localhost.localdomain root[1569] DEBUG https://webpush1.wechat.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_645442450%7C2_45443071%7C3_645442900%7C1000_1479774601&skey=%40crypt_f2a9b885_c3b306210f4481ac9f753177c2c5947&uin=2084815720&r=1479800389&deviceid=e074646143941630&sid=eGeTg%2BpC9x2RY8O&_=1479800389
2016-11-22 15:39:51 localhost.localdomain root[1569] DEBUG https://webpush2.wechat.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_645442450%7C2_645443071%7C3_645442900%7C1000_1479774601&skey=%40crypt_f2a9b885_c3b306210f4481ac975f3177c2c5947&uin=2084815720&r=1479800390&deviceid=e074646143941630&sid=eGeTg%2BpC9x2RY8rO&_=1479800390
2016-11-22 15:39:52 localhost.localdomain root[1569] DEBUG https://webpush.wx.qq.com/cgi-bin/mmwebwx-bin/synccheck?synckey=1_645442450%7C2_645443071%7C3_645442900%7C1000_1479774601&skey=%40crypt_f2a9b885_c3b306210f4481a9f75f317c2c5947&uin=2084815720&r=1479800391&deviceid=e074646143941630&sid=eGeTg%2BpC9xRY8rO&_=1479800391
2016-11-22 15:39:52 localhost.localdomain root[1569] ERROR URLError = [Errno -2] Name or service not known
失败
[*] 退出程序
2016-11-22 15:39:52 localhost.localdomain root[1569] DEBUG [*] 进行同步线路测试 ... ... 失败
2016-11-22 15:39:52 localhost.localdomain root[1569] DEBUG [*] 退出程序
Traceback (most recent call last):
  File "weixin.py", line 1159, in <module>
    webwx.start()
  File "weixin.py", line 32, in wrapper
    return fn(*args)
  File "weixin.py", line 965, in start
    listenProcess.start()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 104, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 99, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 242, in _bootstrap
    sys.stderr.write(e.args[0] + '\n')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
^Z
[8]+  Stopped                 python weixin.py

**Comment by wd** [comment]
试试看 python27

**Comment by star7th** [comment]
Traceback (most recent call last):
  File "weixin.py", line 1159, in <module>
    webwx.start()
  File "weixin.py", line 32, in wrapper
    return fn(*args)
  File "weixin.py", line 927, in start
    self.genQRCode()
  File "weixin.py", line 161, in genQRCode
    self._str2qr('https://login.weixin.qq.com/l/' + self.uuid)
  File "weixin.py", line 1035, in _str2qr
    qr.print_ascii(invert=True)
  File "/usr/local/lib/python2.7/site-packages/qrcode/main.py", line 249, in print_ascii
    out.write(codes[pos])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2588' in position 0: ordinal not in range(128)

**Comment by star7th** [comment]
安装了py2.7，再安装Image，然后现在二维码能在命令行显示了。但随后就是这个错误了。

**Comment by Weilor** [comment]
一般来说还是和系统的编码设置有关系，我直接用weixin.py启动没问题，但是用supervisor启动就会报你这个错误。不过我自己加了邮件功能，可以把二维码发到邮箱去，这部分代码我try了，报错就pass

**Comment by wd** [comment]
那可以试试看 export LANG=zh_CN.UTF-8 (或者是 en_US.UTF-8) ，然后再执行一下 weixin.py

**Comment by star7th** [comment]
centos6、 /etc/sysconfig/i18n文件里关于编码的设置已经是LANG="en_US.UTF-8"了的

**Comment by wd** [comment]
你执行一下 locale 命令，看看输出是什么。

**Comment by star7th** [comment]
locale命令输出的编码依然是系统默认的。也就是说我更改/etc/sysconfig/i18n并没有生效。奇怪了重启也不见生效。关于这个我再找下答案。
现在暂时在命令行执行export LANG=zh_CN.UTF-8是ok了的。先就这样测试下先吧。
