### ISSUE TITLE
启动weixin.py报语法错误

### ISSUE THREAD

**Issue by redrum0003** [Urinx/WeixinBot#157]
$./weixin.py
  File "./weixin.py", line 1068
    def _get(self, url: object, api: object = None) -> object:
                      ^
SyntaxError: invalid syntax

===================
哪位看看是个虾米情况
环境：OSX 10    PYTHON2.7

**Comment by yangwe1** [comment]
这是 type hinting 语法，需要用 python3 环境

**Comment by nazhenhuiyi** [comment]
我看看文档里面是支持2.7的啊.我也遇到了这个问题😅

**Comment by nazhenhuiyi** [comment]
切换到 python3 就👌了

**Comment by nixawk** [comment]
If you want  it in python2, you may use the previous commit.

```
$ git clone https://github.com/Urinx/WeixinBot/
$ git reset --hard 17a8a07d9ba2af9245ee14d41dcf750f523755af
HEAD is now at 17a8a07 Merge pull request #129 from yanxurui/master
$ python weixin.py
....
```

Everything goes well.

**Comment by nazhenhuiyi** [comment]
@nixawk thx

**Comment by leohill33** [comment]
@nazhenhuiyi 你好啊  我换Python3 以后也报错了啊...

> python weixin.py
Traceback (most recent call last):
  File "weixin.py", line 1182, in <module>
    webwx.start()
  File "weixin.py", line 33, in wrapper
    return fn(*args)
  File "weixin.py", line 940, in start
    self._echo('[*] 微信网页版 ... 开动')
  File "weixin.py", line 1037, in _echo
    sys.stdout.write(str)
  File "weixin.py", line 1164, in write
    s = s.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

这个怎么办呢..

**Comment by nixawk** [comment]
I've reviewed the code. Please view https://github.com/nixawk/webwxbot/blob/master/webwxbot.py

**Comment by leohill33** [comment]
@nixawk  THX man, :) do you know any way that I can put in some lines to log the Wechat messages into a log file which the WeixinBot captures?

**Comment by nixawk** [comment]
I guess **logging** is enough. ex:

```
import logging


logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',
    datefmt='%a, %d %b %Y %H:%M:%S',
    filename='webchat.log',
    filemode='w'  # Please attention here.
)

logging.info('WebChat Message')

```

If you need more details, please redirect here:

- https://docs.python.org/3/library/logging.html
- https://pymotw.com/3/logging/index.html

**Comment by leohill33** [comment]
@nixawk awesome,  bro.
