### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by guotie** [Urinx/WeixinBot#160]
环境：
windows 10 64位
python 3.5.2

出错信息：

```
> python weixin.py
Traceback (most recent call last):
  File "weixin.py", line 1182, in <module>
    webwx.start()
  File "weixin.py", line 33, in wrapper
    return fn(*args)
  File "weixin.py", line 940, in start
    self._echo('[*] 微信网页版 ... 开动')
  File "weixin.py", line 1037, in _echo
    sys.stdout.write(str)
  File "weixin.py", line 1164, in write
    s = s.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by eric7166** [comment]
mac 系统：我的根本也运行不了
bogon:WeixinBot yinbing$ python3 weixin.py 
Traceback (most recent call last):
  File "weixin.py", line 22, in <module>
    from lxml import html
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lxml/etree.so, 2): Symbol not found: _PyBaseString_Type
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lxml/etree.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lxml/etree.so

**Comment by leohill33** [comment]
同问

**Comment by leohill33** [comment]
我把1163和1164行注释掉好像就行了
