### ISSUE TITLE
自动模式开启后 报错！

### ISSUE THREAD

**Issue by luxueyan** [Urinx/WeixinBot#206]
```python
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "weixin.py", line 900, in listenMsgMode
    self.handleMsg(r)
  File "weixin.py", line 801, in handleMsg
    ans = self._xiaodoubi(content) + '\n[微信机器人自动回复]'
TypeError: can't concat bytes to str
```

**Comment by CoderOliverz** [comment]
我也是这情况，请问怎么解决？
