### ISSUE TITLE
ImportError: cannot import name 'WeChat'

### ISSUE THREAD

**Issue by yangezheng** [Urinx/WeixinBot#220]
yann@Yannch:~/Projects/WeixinBot/wxbot_project_py2.7$ python3 weixin_bot.py 
Traceback (most recent call last):
  File "weixin_bot.py", line 5, in <module>
    from wechat import WeChat
  File "/home/yann/Projects/WeixinBot/wxbot_project_py2.7/wechat/__init__.py", line 4, in <module>
    from wechat import WeChat
ImportError: cannot import name 'WeChat'

用python3 跑 weixin_bot.py 出现问题

**Comment by michael1589** [comment]
Have you ever resolved? Could you share the method pls?
