### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'setting'

### ISSUE THREAD

**Issue by dev-kang** [Urinx/WeixinBot#241]
Traceback (most recent call last):
  File "weixin_bot.py", line 5, in <module>
    from wechat import WeChat
  File "/Users/DevKang/workspace/devkang/WeixinBot/wxbot_project_py2.7/wechat/__init__.py", line 4, in <module>
    from wechat import WeChat
  File "/Users/DevKang/workspace/devkang/WeixinBot/wxbot_project_py2.7/wechat/wechat.py", line 5, in <module>
    from utils import *
  File "/Users/DevKang/workspace/devkang/WeixinBot/wxbot_project_py2.7/wechat/utils.py", line 5, in <module>
    from config import Log
  File "/Users/DevKang/workspace/devkang/WeixinBot/wxbot_project_py2.7/config/__init__.py", line 6, in <module>
    from log import Log
  File "/Users/DevKang/workspace/devkang/WeixinBot/wxbot_project_py2.7/config/log.py", line 12, in <module>
    cm = ConfigManager()
  File "/Users/DevKang/workspace/devkang/WeixinBot/wxbot_project_py2.7/config/config_manager.py", line 19, in __init__
    data_dir = self.get('setting', 'prefix')
  File "/Users/DevKang/workspace/devkang/WeixinBot/wxbot_project_py2.7/config/config_manager.py", line 27, in get
    return self.cp.get(section, option)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'setting'

**Comment by TonyLianLong** [comment]
请修改config的bak文件为wechat.conf
