### ISSUE TITLE
发送消息时软件奔溃

### ISSUE THREAD

**Issue by xiegeyang** [Urinx/WeixinBot#245]
4029534919478924547 滴雨的屋檐 -> 甜心宝贝我永远爱你: hi
Traceback (most recent call last):
  File "weixin.py", line 1219, in <module>
    webwx.start()
  File "weixin.py", line 36, in wrapper
    return fn(*args)
  File "weixin.py", line 1013, in start
    _thread.start_new_thread(self.listenMsgMode())
  File "weixin.py", line 900, in listenMsgMode
    self.handleMsg(r)
  File "weixin.py", line 801, in handleMsg
    ans = self._xiaodoubi(content) + '\n[微信机器人自动回复]'
TypeError: can't concat str to bytes

**Comment by zsy2504** [comment]
遇到同样的问题，解决了吗？

**Comment by xiegeyang** [comment]
解决了， 我请求了一个pull request， issue#246

**Comment by zsy2504** [comment]
能详细说说么，issue246也没看到啊

**Comment by zsy2504** [comment]
看到了

**Comment by zkailinzhang** [comment]
谢谢 issue246,,但是语音和图片不会回复呢

**Comment by xiegeyang** [comment]
的确， 我没有实现这个功能

**Comment by jf546897** [comment]
4029534919478924547 滴雨的屋檐 -> 甜心宝贝我永远爱你: hi
Traceback (most recent call last):
File "weixin.py", line 1219, in 
webwx.start()
File "weixin.py", line 36, in wrapper
return fn(*args)
File "weixin.py", line 1013, in start
_thread.start_new_thread(self.listenMsgMode())
File "weixin.py", line 900, in listenMsgMode
self.handleMsg(r)
File "weixin.py", line 801, in handleMsg
ans =【self._xiaodoubi(content) +】 '\n[微信机器人自动回复]'
TypeError: can't concat str to bytes

去掉大括号里面的一段，delete 【self._xiaodoubi(content) +】
