### ISSUE TITLE
自动回复功能报错

### ISSUE THREAD

**Issue by zhfff4869** [Urinx/WeixinBot#272]
[*] 进行同步线路测试 ... ERROR:root:URLError = timed out
成功
不能自动回复，报错：typeerror

**Comment by zhfff4869** [comment]
7563122074624064091 彼此弯弓月 -> 落虹桥月: 你好
Traceback (most recent call last):
  File "E:/Personal/Desktop/自然语言处理/WeixinBot-master/wxbot_demo_py3/weixin.py", line 1219, in <module>
    webwx.start()
  File "E:/Personal/Desktop/自然语言处理/WeixinBot-master/wxbot_demo_py3/weixin.py", line 36, in wrapper
    return fn(*args)
  File "E:/Personal/Desktop/自然语言处理/WeixinBot-master/wxbot_demo_py3/weixin.py", line 1013, in start
    _thread.start_new_thread(self.listenMsgMode())
  File "E:/Personal/Desktop/自然语言处理/WeixinBot-master/wxbot_demo_py3/weixin.py", line 900, in listenMsgMode
    self.handleMsg(r)
  File "E:/Personal/Desktop/自然语言处理/WeixinBot-master/wxbot_demo_py3/weixin.py", line 801, in handleMsg
    ans = self._xiaodoubi(content) + '\n[微信机器人自动回复]'
TypeError: can't concat str to bytes

进程已结束，退出代码 1
