### ISSUE TITLE
扫码登录失败报错 

### ISSUE THREAD

**Issue by YanJiarui-AN** [Urinx/WeixinBot#303]
报错内容：
[*] 微信网页版 ... 开动
[*] 正在获取 uuid ... 成功
[*] 正在获取二维码 ... 成功
[*] 请使用微信扫描二维码以登录 ... 
[*] 正在登录 ... ERROR:root:generic exception: Traceback (most recent call last):
  File "D:\Desktop\WeixinBot-master\wxbot_demo_py3\weixin.py", line 1109, in _get
    data = response.read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 339: invalid continuation byte

失败
[*] 退出程序

有哪位大神能帮忙看一看

**Comment by DeSireFire** [comment]
> 报错内容： [_] 微信网页版 ... 开动 [_] 正在获取 uuid ... 成功 [_] 正在获取二维码 ... 成功 [_] 请使用微信扫描二维码以登录 ... [*] 正在登录 ... ERROR:root:generic exception: Traceback (most recent call last): File "D:\Desktop\WeixinBot-master\wxbot_demo_py3\weixin.py", line 1109, in _get data = response.read().decode('utf-8') UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 339: invalid continuation byte
> 
> 失败 [*] 退出程序
> 
> 有哪位大神能帮忙看一看

今天做了一下尝试，感觉这个项目年久失修了：
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, viewport-fit=cover" />
    <meta name="color-scheme" content="light dark">
    <title>微信网页版</title>
    <style>
      * {
        margin: 0;
        padding: 0;
      }
      body {
        font-family: Microsoft YaHei,-apple-system-font,Helvetica Neue,Helvetica,sans-serif;
        font-size: 14px;
        line-height: 1.6;
      }
      .msg {
        width: 400px;
        margin: 0 auto;
        text-align: center;
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
      }
      .msg-title {
        font-size: 24px;
        font-weight: 400;
        color: #191919;
      }
      @media (prefers-color-scheme: dark) {
        .msg-title {
          color: rgba(255, 255, 255, 0.9);
        }
      }
      .msg-desc {
        margin-top: 10px;
        font-weight: 400;
        color: #999999;
        word-break: break-word;
      }
      .msg-button-area {
        margin-top: 72px;
      }
      .msg-button {
        width: 228px;
        height: 32px;
        background-color: #07C160;
        border: 0;
        color: #fff;
        border-radius: 3px;
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        line-height: 32px;
        text-decoration: none;
      }
      .msg-button:hover {
        background-color: #06ad56;
      }
    </style>
  </head>
  <body>
    <div class="msg">
      <div class="msg-text-area">
        <p class="msg-desc">为了保障你的账号安全，暂不支持使用网页版微信。你可以前往微信官网&nbsp;https://weixin.qq.com/&nbsp;下载客户端登录。</p>
      </div>
          </div>
  <script src="//res.wx.qq.com/t/wx_fed/webwx/res/static/vendor/vendor_4bfe99c.js"></script><script>webpackJsonp([0],[function(n,exports){n.exports=""}]);/* vhtml-webpack-plugin version: 0.1.38 */</script></body>
</html>

```

**Comment by jinde98** [comment]
微信取消网页版登录了

**Comment by Nanssr** [comment]
现在解决了吗？我刚刚也遇到了这个问题
