### ISSUE TITLE
遇到了问题pickle.PicklingError: Can't pickle <type 'thread.lock'>: it's not found as thread.lock

### ISSUE THREAD

**Issue by WeiYongqiang55** [Urinx/WeixinBot#45]
我遇到了这个问题

D:\pythoncode\WeixinBot-master>python weixin.py
[_] 微信网页版 ... 开动
[32m2016-04-26 18:37:55[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 寰俊缃戦
〉鐗?... 寮€鍔?[0m
[_] 正在获取 uuid ... 成功
[32m2016-04-26 18:37:56[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 姝ｅ湪鑾峰
彇 uuid ... ... 鎴愬姛[0m
[_] 正在获取二维码 ... 成功
[32m2016-04-26 18:37:56[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 寰俊缃戦
〉鐗?... 寮€鍔?[0m
[32m2016-04-26 18:37:56[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32mSaved file: D:
\pythoncode\WeixinBot-master\saved\qrcodes\qrcode.jpg[0m
[_] 请使用微信扫描二维码以登录 ...
[32m2016-04-26 18:38:19[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32mhttps://login.
weixin.qq.com/cgi-bin/mmwebwx-bin/login?tip=1&uuid=gZk_oobn_A==&_=1461667077[0m
[32m2016-04-26 18:38:24[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32mhttps://login.
weixin.qq.com/cgi-bin/mmwebwx-bin/login?tip=0&uuid=gZk_oobn_A==&_=1461667099[0m
[_] 正在登录 ... [32m2016-04-26 18:38:24[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [
32mhttps://wx.qq.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=AQaDOYZ8rqoj9G5rbLvDeDKr@qrticket_0
&uuid=gZk_oobn_A==&lang=zh_CN&scan=1461667105&fun=new[0m
成功
[32m2016-04-26 18:38:24[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 姝ｅ湪鐧诲
綍 ... ... 鎴愬姛[0m
[_] 微信初始化 ... 成功
[32m2016-04-26 18:38:25[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 寰俊鍒濆
鍖?... ... 鎴愬姛[0m
[_] 开启状态通知 ... 成功
[32m2016-04-26 18:38:25[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 寮€鍚姸
鎬侀€氱煡 ... ... 鎴愬姛[0m
[_] 获取联系人 ... https://wx.qq.com/cgi-bin/mmwebwx-bin
成功
[32m2016-04-26 18:38:27[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 鑾峰彇鑱旂
郴浜?... ... 鎴愬姛[0m
[_] 应有 415 个联系人，读取到联系人 415 个
[_] 共有 6 个群 | 171 个直接联系人 | 0 个特殊账号 ｜ 237 公众号或服务号
[_] 获取群 ... 成功
[32m2016-04-26 18:38:27[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 鑾峰彇缇?.
.. ... 鎴愬姛[0m
[32m2016-04-26 18:38:27[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 寰俊缃戦
〉鐗?... 寮€鍔?[0m
# [32m2016-04-26 18:38:27[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m==============

[#] Web Weixin
[#] Debug Mode: False
[#] Uuid: gZk_oobn_A==
[#] Uin: 1583421542
[#] Sid: VbGA+vSkmv+FM+dR
[#] Skey: @crypt_927e477f_ef7c0a891a77b236dc3c5b8f7c8450f1
[#] DeviceId: e834504991840841
[#] PassTicket: WbDwR0GtAYVoQNH15Ue14oBsClOPSeGCG09xtzTzp85IdW76er5OyegSP9gtbLpI
=========================[0m
[_] 自动回复模式 ... 关闭
[32m2016-04-26 18:38:27[0m [35mGunshoot[0m [34mroot[3628][0m [30mDEBUG[0m [32m[_] 鑷姩鍥炲
妯″紡 ... 鍏抽棴[0m
Traceback (most recent call last):
  File "weixin.py", line 1046, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 347, in main
        wself = load(from_parent)
ebwx.start()
  File "C:\Python27\lib\pickle.py", line 1378, in load
  File "weixin.py", line 30, in wrapper
    return fn(*args)
  File "weixin.py", line 887, in start
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 858, in load
    listenProcess.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 104, in start
        dispatch[key](self)
s  File "C:\Python27\lib\pickle.py", line 880, in load_eof
elf._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 244, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
     raise EOFError
 File "C:\Python27\lib\multiprocessing\forking.py", line 167, in dump
EOFError
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\multiprocessing\forking.py", line 40, in dispatcher
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 548, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 725, in save_inst
    save(stuff)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 396, in save_reduce
    save(cls)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <type 'thread.lock'>: it's not found as thread.lock

**Comment by msly** [comment]
multiprocessing 在python2.7的问题

**Comment by keyhua11** [comment]
请问如何解决啊？ @msly

**Comment by keyhua11** [comment]
解决问题了。用threading代替multiprocessing
把这几行替换掉
        listenProcess = multiprocessing.Process(target=self.listenMsgMode)

##         listenProcess.start()

import threading
        listenProcess = threading.Thread(target=self.listenMsgMode)
        listenProcess.start()
        listenProcess.join()

**Comment by ferstar** [comment]
@keyhua11 `listenProcess.join()`最好注释掉, 不然会停在`listenMsgMode`里没法继续下面的输入监听了

**Comment by tylor-e** [comment]
换了这个之后，输入quit说thread没有terminate

listenProcess.terminate()

**Comment by fufuhoshizora** [comment]
请问为什么会输出�[32m2016-04-26 18:37:55�[0m �[35mGunshoot�[0m �[34mroot[3628]�[0m �[30mDEBUG�[0m �[32m[] 寰俊缃戦
〉鐗?... 寮€鍔?[0m
这些？
我也有这些输出。
