### ISSUE TITLE
请问windows能跑吗？

### ISSUE THREAD

**Issue by faace** [Urinx/WeixinBot#70]
我在windows下，用pip install requests，中途就失败了，

`adthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    8% |██▋                             | 40kB 6.1kB/s eta 0:01:17Exception:
Traceback (most recent call last):
  File "c:\python\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python\lib\site-packages\pip\req\req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\python\lib\site-packages\pip\download.py", line 810, in unpack_url
    hashes=hashes
  File "c:\python\lib\site-packages\pip\download.py", line 649, in unpack_http_url
    hashes)
  File "c:\python\lib\site-packages\pip\download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "c:\python\lib\site-packages\pip\download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\python\lib\site-packages\pip\utils\hashes.py", line 46, in check_against_chunks
    for chunk in chunks:`

**Comment by xelmirage** [comment]
包安装错误啊……你可以下载一个winpython试试，自带了好多包，然后按照提示把缺的补上应该就好

**Comment by EvilBandit** [comment]
我使用windows跑的，前面没有问题，但是运行到自动回复那边就开始报错了，还没解决。。。

**Comment by xelmirage** [comment]
winpython的意思不是windows下的python-，-是一个自带齐全的包的python发行版……
